### ISSUE TITLE
Show the pinned posts first (top) on list pages

### ISSUE THREAD

**Issue by gavlinski** [hbstack/blog#1113]
The statistics (taxonomies?) and the carousel/featured posts are shown in the same way on the home page and the blog (list page). When the carousel is visible, the pinned posts are also displayed normally next to it (right side). However, the listing order (just below) in the paginated items changes: on the home page, the pinned posts appear first, while on the list page the posts always appear in chronological order (most recent to less recent).

I suggest adding an option in which the user can define the layout or the order in which the items (posts or docs) are displayed on the pagination, considering or not the priority of the pinned items.

**Comment by razonyang** [comment]
Available since [v0.42.0](https://github.com/hbstack/blog/releases/tag/v0.42.0), you can control how many pinned posts to be shown via `hb.blog.list_pinned_posts` parameter, `false` to disable it.

**Comment by razonyang** [comment]
Hmm, I think you're still misunderstand the list and homepage, which `layout = index` means homepage, `/` typically is also a homepage if no layout specified.

So let us make this request clear, do you want to show the pinned posts on **homepage** (`index` layout) rather than the list pages?

**Comment by razonyang** [comment]
Hmm, seems something wrong, since I don't see such issue in https://theme.hbstack.dev/ and https://razonyang.com/zh-hans, do you have a repo for reproducing this issue? What the URL path you're visiting.

**Comment by gavlinski** [comment]
I'm using the [HB Starter Theme Template](https://theme.hbstack.dev/) but with the latest module updates. What I think may have happened is that some of the new modules have changed the original default way the files in `/content/blog` work. Below I've pasted the contents of the current `go.mod` and `config/_default/module.yaml` files. Please let me know if you need more data to debug.

Here is a summary of all the test scenarios I could reproduced here:

1. ✅ **Homepage in `/`**, file `/content/_index.md` with front matter containing only the title:
   - pinned test doc page **always displayed** as the first result
   - works even with `hb.blog.list_pinned_posts: false`
   - always worked as expected even before the new update
&nbsp;
2. ✅ **Blog in `/content/blog`**, file `/content/blog/_index.md` with front matter containing **`layout: list`** (same as the previous message):
   - pinned test post page displayed as the first result **after the new blog modulo update**
   - works only with `hb.blog.list_pinned_posts: 1` or greater
   - worked previously and still works in the version published at https://theme.hbstack.dev/en/blog/ (has old versions?), stopped working after some module update applied here locally
   - shows the breadcrumbs
&nbsp;
3. ❌ **Blog in `/content/blog`**, file `/content/blog/_index.md` with front matter containing **`layout: index` or nothing**:
   - pinned test post page displayed in **chronological order** according to its date
   - does not work with any `hb.blog.list_pinned_posts` configuration
   - the red pin icon is displayed on the left side, which indicates that the post `pinned: true` is being listed, although not in the first position
   - does not show the breadcrumbs anymore

Scenario 2 solves the problem for me. However, it should also work in scenario 3, that is, it should not be mandatory to inform `layout: list` for the blog, or this should be the default option as it was before, but maybe it is being overridden or ignored somehow.

I hope I was able to explain. If you need more information or think it is not worth investigating, just let me know.
Thank you for your understanding and willingness to help!

`go.mod` file content:

```
module gitlab.com/internal-server/community-version/my-repo

go 1.19

require (
	github.com/GoogleChrome/workbox v7.3.0+incompatible // indirect
	github.com/KaTeX/KaTeX v0.16.22 // indirect
	github.com/Templarian/MaterialDesign-SVG v7.4.47+incompatible // indirect
	github.com/desandro/masonry v4.2.2+incompatible // indirect
	github.com/feathericons/feather v4.29.2+incompatible // indirect
	github.com/gohugoio/hugo-mod-bootstrap-scss/v5 v5.20300.20400 // indirect
	github.com/gohugoio/hugo-mod-jslibs-dist/popperjs/v2 v2.21100.20000 // indirect
	github.com/hbstack/back-to-top v0.2.0 // indirect
	github.com/hbstack/base v0.6.2 // indirect
	github.com/hbstack/bigger-picture v0.10.1 // indirect
	github.com/hbstack/blockquote-alerts v0.1.1 // indirect
	github.com/hbstack/blog v0.42.0 // indirect
	github.com/hbstack/blog/modules/breadcrumb v0.1.23 // indirect
	github.com/hbstack/blog/modules/content-panel v0.1.21 // indirect
	github.com/hbstack/blog/modules/featured-image v0.2.21 // indirect
	github.com/hbstack/blog/modules/heading-sign v0.1.23 // indirect
	github.com/hbstack/blog/modules/post-nav v0.4.0 // indirect
	github.com/hbstack/blog/modules/related-posts v0.4.0 // indirect
	github.com/hbstack/blog/modules/revision v0.1.0 // indirect
	github.com/hbstack/blog/modules/sidebar/posts v0.8.0 // indirect
	github.com/hbstack/blog/modules/sidebar/profile v1.3.0 // indirect
	github.com/hbstack/blog/modules/sidebar/taxonomies v0.5.0 // indirect
	github.com/hbstack/blog/modules/toc-scrollspy v0.2.0 // indirect
	github.com/hbstack/bootstrap v0.2.2 // indirect
	github.com/hbstack/breadcrumb v0.8.0 // indirect
	github.com/hbstack/bs-tooltip v0.1.1 // indirect
	github.com/hbstack/carousel v0.2.7 // indirect
	github.com/hbstack/code-block-panel v0.1.2 // indirect
	github.com/hbstack/content-panel v0.10.2 // indirect
	github.com/hbstack/docs v0.23.1 // indirect
	github.com/hbstack/docs/modules/breadcrumb v0.1.10 // indirect
	github.com/hbstack/docs/modules/content-panel v0.1.8 // indirect
	github.com/hbstack/docs/modules/doc-nav v0.3.7 // indirect
	github.com/hbstack/docs/modules/featured-image v0.2.8 // indirect
	github.com/hbstack/docs/modules/heading-sign v0.1.9 // indirect
	github.com/hbstack/docs/modules/revision v0.1.0 // indirect
	github.com/hbstack/docs/modules/toc-scrollspy v0.1.8 // indirect
	github.com/hbstack/featured-image v0.2.2 // indirect
	github.com/hbstack/footer v0.4.1 // indirect
	github.com/hbstack/footer/modules/socials v0.3.0 // indirect
	github.com/hbstack/gallery v0.13.1 // indirect
	github.com/hbstack/gallery/modules/breadcrumb v0.1.1 // indirect
	github.com/hbstack/hb v0.16.2 // indirect
	github.com/hbstack/header v0.16.6 // indirect
	github.com/hbstack/header/modules/git-repo v0.4.3 // indirect
	github.com/hbstack/header/modules/language-picker v0.2.0 // indirect
	github.com/hbstack/header/modules/news v0.3.1 // indirect
	github.com/hbstack/header/modules/search v0.1.38 // indirect
	github.com/hbstack/header/modules/socials v0.2.2 // indirect
	github.com/hbstack/header/modules/theme-toggle v0.5.2 // indirect
	github.com/hbstack/header/themes/pills v0.2.18 // indirect
	github.com/hbstack/heading-sign v0.2.0 // indirect
	github.com/hbstack/mermaid v0.2.2 // indirect
	github.com/hbstack/meta/recommended v0.2.10 // indirect
	github.com/hbstack/noscript v0.7.0 // indirect
	github.com/hbstack/pagination v0.8.0 // indirect
	github.com/hbstack/progress-bar v0.1.1 // indirect
	github.com/hbstack/pwa v0.1.2 // indirect
	github.com/hbstack/revision v0.6.9 // indirect
	github.com/hbstack/scrollbar v0.1.0 // indirect
	github.com/hbstack/search v0.2.2 // indirect
	github.com/hbstack/shortcodes v0.2.0 // indirect
	github.com/hbstack/slide v0.4.1 // indirect
	github.com/hbstack/snackbar v0.1.2 // indirect
	github.com/hbstack/socials v0.18.0 // indirect
	github.com/hbstack/syntax-highlighting v0.2.1 // indirect
	github.com/hbstack/syntax-highlighting/styles/github-dark v0.1.2 // indirect
	github.com/hbstack/syntax-highlighting/styles/gruvbox v0.1.2 // indirect
	github.com/hbstack/toc-scrollspy v0.2.0 // indirect
	github.com/henrygd/bigger-picture v1.1.19 // indirect
	github.com/hugomods/ascii v0.1.0 // indirect
	github.com/hugomods/base v0.7.3 // indirect
	github.com/hugomods/bootstrap v0.23.0 // indirect
	github.com/hugomods/code-block-panel v0.8.0 // indirect
	github.com/hugomods/font-awesome v6.7.1+incompatible // indirect
	github.com/hugomods/fuse-js v0.1.0 // indirect
	github.com/hugomods/gravatar v0.2.1 // indirect
	github.com/hugomods/hugopress v0.5.0 // indirect
	github.com/hugomods/i18n-js v0.2.1 // indirect
	github.com/hugomods/icons v0.6.6 // indirect
	github.com/hugomods/icons/vendors/bootstrap v0.5.11 // indirect
	github.com/hugomods/icons/vendors/feather v0.2.7 // indirect
	github.com/hugomods/icons/vendors/font-awesome v0.6.12 // indirect
	github.com/hugomods/icons/vendors/lucide v0.3.40 // indirect
	github.com/hugomods/icons/vendors/mdi v0.3.8 // indirect
	github.com/hugomods/icons/vendors/simple-icons v1.1.1 // indirect
	github.com/hugomods/icons/vendors/tabler v0.15.53 // indirect
	github.com/hugomods/idb-js v0.1.0 // indirect
	github.com/hugomods/images v0.12.3 // indirect
	github.com/hugomods/katex v0.3.6 // indirect
	github.com/hugomods/lucide-icons v0.331.0 // indirect
	github.com/hugomods/masonry-js v0.1.0 // indirect
	github.com/hugomods/mermaid v0.1.4 // indirect
	github.com/hugomods/pwa v0.9.0 // indirect
	github.com/hugomods/search v0.20.0 // indirect
	github.com/hugomods/search-index v0.1.2 // indirect
	github.com/hugomods/seo/modules/alternatives v0.1.1 // indirect
	github.com/hugomods/seo/modules/base v0.1.3 // indirect
	github.com/hugomods/seo/modules/favicons v0.2.2 // indirect
	github.com/hugomods/seo/modules/open-graph v0.1.1 // indirect
	github.com/hugomods/seo/modules/schema v0.1.3 // indirect
	github.com/hugomods/seo/modules/translations v0.1.1 // indirect
	github.com/hugomods/seo/modules/twitter-cards v0.1.1 // indirect
	github.com/hugomods/shortcodes v0.25.1 // indirect
	github.com/hugomods/simple-icons v13.21.0+incompatible // indirect
	github.com/hugomods/snackbar v0.1.2 // indirect
	github.com/hugomods/video-js v0.3.0 // indirect
	github.com/hugomods/workbox v0.1.0 // indirect
	github.com/jakearchibald/idb v8.0.3+incompatible // indirect
	github.com/krisk/Fuse v7.1.0+incompatible // indirect
	github.com/tabler/tabler-icons v3.34.0+incompatible // indirect
	github.com/twbs/bootstrap v5.3.7+incompatible // indirect
	github.com/twbs/icons v1.13.1 // indirect
)
```

`config/_default/module.yaml` file content:

```yaml
# For some regions can not access the proxy.golang.org, i.e. China.
# See https://hugomods.com/en/blog/2023/04/go-and-hugo-proxy-servers/ for all available proxy servers.
# proxy: https://goproxy.cn,direct

# The order of module is very important, precedence from top to bottom.
imports:
  - path: github.com/hbstack/blockquote-alerts
  - path: github.com/hbstack/bs-tooltip
  - path: github.com/hbstack/shortcodes
  - path: github.com/hugomods/video-js

  # gallery modules
  - path: github.com/hbstack/gallery
  - path: github.com/hbstack/gallery/modules/breadcrumb

  # syntax highlighting, see https://hbstack.dev/en/docs/modules/syntax-highlighting/.
  - path: github.com/hbstack/syntax-highlighting/styles/github-dark

  # icons modules
  - path: github.com/hugomods/icons/vendors/bootstrap
  - path: github.com/hugomods/icons/vendors/feather
  - path: github.com/hugomods/icons/vendors/font-awesome
  - path: github.com/hugomods/icons/vendors/lucide
  - path: github.com/hugomods/icons/vendors/mdi
  - path: github.com/hugomods/icons/vendors/simple-icons
  - path: github.com/hugomods/icons/vendors/tabler

  # header themes
  - path: github.com/hbstack/header/themes/pills

  # blog sidebar
  - path: github.com/hbstack/blog/modules/sidebar/profile
  - path: github.com/hbstack/blog/modules/sidebar/posts
  - path: github.com/hbstack/blog/modules/sidebar/taxonomies

  # blog table of contents scrollspy
  - path: github.com/hbstack/blog/modules/toc-scrollspy

  # blog content panel
  - path: github.com/hbstack/blog/modules/content-panel

  # blog revision date
  - path: github.com/hbstack/blog/modules/revision

  # docs table of contents scrollspy
  - path: github.com/hbstack/docs/modules/toc-scrollspy

  # docs content panel
  - path: github.com/hbstack/docs/modules/content-panel

  # docs revision date
  - path: github.com/hbstack/docs/modules/revision

  # header news module
  - path: github.com/hbstack/header/modules/news

  # recommended modules
  # check which modules were imported by recommended module by "hugo mod graph | grep recommended".
  # see also https://hbstack.dev/en/docs/modules/meta/.
  # to remove unused modules, you need to replace the recommended module with modules your need.
  # see also https://hbstack.dev/en/2023/10/replace-meta-modules/.
  - path: github.com/hbstack/meta/recommended
```
